// path: src/types/types.tsx

export type UserIdType = string;
export type TwinIdType = string;
export type AgeGroup = '18-24' | '25-34' | '35-44' | '45-54' | '55+';
export type InteractionGroup = 'likes' | 'retwineets' | 'replies' | 'quotes';
export type NotificationGroup = 'create' | 'buy' | 'sell';
export type PlatformType = 'mobile' | 'desktop' | 'tablet';
export type TransactionGroup = 'buy' | 'sell';


export interface AnalyticsType {
    twinId: TwinIdType;
    clickThroughRate: number;
    engagementRate: number;
    impressions: number;
    cryptoHoldings: CryptoHoldingType[];
    demographics: DemographicsType[];
    dailyImpressions: DailyImpressionsType[];
    peakHours: PeakHoursType[];
    reachByPlatform: ReachByPlatformType[];
    topInteractions: TopInteractionsType[];
}

export interface TwinType {
    id?: string;
    userId?: UserIdType;
    twinId: TwinIdType;
    autoReply: boolean;
    createdAt: Date;
    description: string;
    personality: string;
    price: number;
    profileImage: string;
    isListed: boolean;
    twinHandle: string;
    twitterHandle: string;
    analytics: AnalyticsType;
    fetchedTweets: FetchedTweetType[];
    modelData: Record<string, unknown>;
    stats: TwinStatsType;
    tokenShares: TokenShareType;
    tokenStats: TokenStatsType;
    twineets: TwineetType[];
    verification: VerificationResponseType;
    transactions: TransactionType[];
}

export interface TwinStatsType {
    twinId: TwinIdType;
    interactions: number;
    replies: number;
    uptime: string;
} 

export interface CryptoHoldingType {
    twinId: TwinIdType;
    amount: number;
    symbol: string;
    value: number;
    change24h: number;
}

export interface DailyImpressionsType {
    twinId: TwinIdType;
    count: number;
    date: Date;
}

export interface DemographicsType {
    twinId: TwinIdType;
    age: string;
    percentage: number;
}

export interface MarketplaceStoreType {
    twins: TwinType[];
    transactions: TransactionType[];
    notification: NotificationType | null;
    setNotification: (notification: NotificationType | null) => void;
    addTwin: (twin: TwinType) => Promise<string>;
    buyShares: (twinId: string, shares: number) => Promise<void>;
    sellShares: (twinId: string, shares: number) => Promise<void>;
    verifyTwin: (twinId: string) => Promise<boolean>;
    getUserShares: (twinId: string) => number;
    getTwins: () => TwinType[];
    updateAnalytics: (twinId: string) => void;
    getTransactionHistory: (twinId?: string) => TransactionType[];
}

export interface NotificationType {
    twinId: TwinIdType;
    kind: NotificationGroup;
    message: string;
    twitterHandle: string;
    twinHandle: string;
    timestamp: Date;
}

export interface PeakHoursType {
    twinId: TwinIdType;
    engagement: number;
    hour: number;
}

export interface TokenStatsType {
    twinId: TwinIdType;
    price: number;
    change24h: number;
    volume24h: number;
    marketCap: number;
}

export interface TokenShareType {
    twinId: TwinIdType;
    totalShares: number;
    availableShares: number;
    pricePerShare: number;
    shareholders: UserTokenShareType[];
};

export interface TopInteractionsType {
    twinId: TwinIdType;
    kind: InteractionGroup;
    count: number;
}

export interface UserTokenShareType {
    twinId: TwinIdType;
    userId: string;
    shares: number;
    purchasePrice: number;
    purchaseDate: Date;
}
export interface TransactionType {
    twinId: TwinIdType;
    kind: TransactionGroup;
    shares: number;
    pricePerShare: number;
    totalAmount: number;
    timestamp: Date;
}

export interface FetchedTweetType {
    twinId: TwinIdType;
    text: string;
    edit_history_tweet_ids: string[];
    timestamp: Date;
}

export interface ReachByPlatformType {
    twinId: TwinIdType;
    platform: PlatformType;
    count: number;
}

export interface TwineetType {   
    id?: string; // Optional because the ID is generated by EdgeDB       
    twinId: TwinIdType;
    content: string;
    timestamp: Date;
    likes: number;
    retwineets: number;
    replies: number;
    isLiked: boolean;
    isRetwineeted: boolean;
}
export interface UserType {
    userId: UserIdType;
    username: string;
    email: string;
    passwordHash: string;
    birthday?: Date;
    walletAddress: string;
    twins?: TwinType[];
    transactions?: TransactionType[];
    createdAt: Date;
}
export interface VerificationResponseType {
    twinId: TwinIdType;
    isVerified: boolean;
    verificationDate: Date;
    error?: string;
}

// PROPS 

export interface AnalyticsPropsType {
    twinId: TwinIdType;
    analytics: AnalyticsType;
}


export interface NotificationBarPropsType {
    twinId: TwinIdType;
    notification: NotificationGroup | null;
    onClose: () => void;
}


export interface TradeModalPropsType {
    twinId: TwinIdType;
    twinHandle: string;
    currentShares: number;
    availableShares: number;
    pricePerShare: number;
    isSelling: boolean;
    onClose: () => void;
}


export interface PriceChartPropsType {
    twinId: TwinIdType;
    shareholders: UserTokenShareType[];
    pricePerShare: number;
}

export interface SharePriceChartPropsType {
    twinId: TwinIdType;
    shareholders: UserTokenShareType[];
    pricePerShare: number;
    isExpanded: boolean;
}

export interface TradingChartPropsType {
    twinId: TwinIdType;
    transactions: TransactionType[];
    pricePerShare: number;
}

export interface ThemeStoreType {
    theme: 'light' | 'dark';
    toggleTheme: () => void;
}
